name: final_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  flutter_svg: ^2.0.17
  equatable: ^2.0.7
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.4
  http: ^1.3.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.3
  pretty_http_logger: ^1.0.5
  easy_localization: ^3.0.7+1
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.1
  audioplayers: ^6.4.0
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Group.png"
  android_background_color: "#051754"  # replace with your desired hex color
  ios_background_color: "#051754"  

flutter:
  uses-material-design: true
  assets:
   - assets/icons/avatar.png
   - assets/icons/Group.png
   - assets/icons/formal.jpg
   - assets/translations/
   - assets/sounds/
